### ISSUE TITLE
Better condition to check if hash_salt is set

### ISSUE THREAD

**Issue by hugronaphor** [platformsh-templates/drupal8-multisite#33]
https://github.com/platformsh-templates/drupal8-multisite/blob/ee8a4810e61950ca3b7ec833ff4c3204acd884ec/web/sites/settings.platformsh.php#L123

Normally, the default `settings.php` comes with `$settings['hash_salt'] = '';` so the `??` won't catch this case.

`?:` would be needed or a proper `empty()` check to handle all cases.

**Comment by chadwcarlson** [comment]
Setting updated in https://github.com/platformsh-templates/drupal8-multisite/pull/35
